//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldCPUSimulatorGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OldCPUSimulatorGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CPU&apos;s clock speed could not be determined..
        /// </summary>
        internal static string CPUSpeedNotDetermined {
            get {
                return ResourceManager.GetString("CPUSpeedNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must not run multiple instances of Old CPU Simulator..
        /// </summary>
        internal static string NoMultipleInstances {
            get {
                return ResourceManager.GetString("NoMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old CPU could not be simulated..
        /// </summary>
        internal static string OldCPUNotSimulated {
            get {
                return ResourceManager.GetString("OldCPUNotSimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old CPU Simulator Process failed to be created..
        /// </summary>
        internal static string OldCPUSimulatorProcessFailedCreate {
            get {
                return ResourceManager.GetString("OldCPUSimulatorProcessFailedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a file first (or click New.).
        /// </summary>
        internal static string SelectFileFirst {
            get {
                return ResourceManager.GetString("SelectFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target Rate must not be greater than or equal to the Max Rate of {0:D}..
        /// </summary>
        internal static string TargetRateMaxRate {
            get {
                return ResourceManager.GetString("TargetRateMaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target Rate must not be zero..
        /// </summary>
        internal static string TargetRateNotZero {
            get {
                return ResourceManager.GetString("TargetRateNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target Rate must be a valid number..
        /// </summary>
        internal static string TargetRateValidNumber {
            get {
                return ResourceManager.GetString("TargetRateValidNumber", resourceCulture);
            }
        }
    }
}
