//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldCPUSimulatorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString0 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString0"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString1 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString1"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString2 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString2"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString3 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString3"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString4 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString4"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString5 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString5"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString6 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString6"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString7 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString7"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString8 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString8"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUSimulatorSaveDataRecentFilesListBoxItemString9 {
            get {
                return ((string)(this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString9"]));
            }
            set {
                this["oldCPUSimulatorSaveDataRecentFilesListBoxItemString9"] = value;
            }
        }
    }
}
