//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldCPUEmulatorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString0 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString0"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString1 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString1"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString2 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString2"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString3 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString3"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString4 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString4"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString5 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString5"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString6 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString6"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString7 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString7"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString8 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString8"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldCPUEmulatorSaveDataRecentFilesListBoxItemString9 {
            get {
                return ((string)(this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString9"]));
            }
            set {
                this["oldCPUEmulatorSaveDataRecentFilesListBoxItemString9"] = value;
            }
        }
    }
}
